### ISSUE TITLE
Cannot fetch help through RStudio

### ISSUE THREAD

**Issue by gungorbudak** [montilab/hypeR#11]
When RStudio tries to fetch help for the package I get this error

```
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/hypeR/help/hypeR.rdb' is corrupt
```

Triggered when I press Tab in `hypeR()` function parantheses to see what options available.

**Comment by anfederico** [comment]
It's likely due to upgrading the package. A couple functions were changed in the latest version. 

- Restart R Studio so hypeR isn't loaded 
- `remove.packages("hypeR")`
- `devtools::install_github("montilab/hypeR")`

**Comment by gungorbudak** [comment]
Thanks, the errors disappeared now, I believe `??hypeR` wasn't supposed to work anyway right? I'm expecting to see its documents on the right panel.

![Screen Shot 2019-12-16 at 13 39 03](https://user-images.githubusercontent.com/1062679/70900309-98e28d00-2009-11ea-934f-1716c026f308.png)

**Comment by anfederico** [comment]
Try `help("hypeR")` or `?hypeR`

**Comment by gungorbudak** [comment]
Cool, those work. Previously they were not working so I was trying `??hyper`. Thanks very much!
