### ISSUE TITLE
Run enrichment on gene sets below some size and above some percentage

### ISSUE THREAD

**Issue by gungorbudak** [montilab/hypeR#12]
Does hypeR have an option where we can filter out very large gene sets? I'd like to set a threshold like 900 so it doesn't do enrichment on gene sets with that and above size. Currently I can post-filter results which is fine too but this can be a nice improvement.

There can also be option to filter out gene sets with minimum percentage. Say only return gene sets where data and the gene set share more than 2% of the genes.

Thanks!

**Comment by anfederico** [comment]
This is a good suggestion. Currently there isn't a built-in way, but the `gsets` object is simple and can be modified in the following way without losing any downstream functionality.

``` r
library(hypeR)

KEGG <- msigdb_gsets("Homo sapiens", "C2", "CP:KEGG")
print(KEGG)
#> C2.CP:KEGG v7.0.1
#> KEGG_ABC_TRANSPORTERS (44)
#> KEGG_ACUTE_MYELOID_LEUKEMIA (57)
#> KEGG_ADHERENS_JUNCTION (73)
#> KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY (67)
#> KEGG_ALANINE_ASPARTATE_AND_GLUTAMATE_METABOLISM (32)
#> KEGG_ALDOSTERONE_REGULATED_SODIUM_REABSORPTION (42)

# Filter by size
KEGG$genesets <- KEGG$genesets[unlist(lapply(KEGG$genesets, function(x) length(x) < 50))]

print(KEGG)
#> C2.CP:KEGG v7.0.1
#> KEGG_ABC_TRANSPORTERS (44)
#> KEGG_ALANINE_ASPARTATE_AND_GLUTAMATE_METABOLISM (32)
#> KEGG_ALDOSTERONE_REGULATED_SODIUM_REABSORPTION (42)
#> KEGG_ALLOGRAFT_REJECTION (37)
#> KEGG_ALPHA_LINOLENIC_ACID_METABOLISM (19)
#> KEGG_AMINO_SUGAR_AND_NUCLEOTIDE_SUGAR_METABOLISM (44)
```

<sup>Created on 2019-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The same logic goes for your second suggestion.
