### ISSUE TITLE
 msigdb_gsets doesn't give me all the CP gene sets

### ISSUE THREAD

**Issue by gungorbudak** [montilab/hypeR#13]
Hi,

I just reinstalled `hypeR` from its GitHub master branch and tried following to obtain canonical pathways from MSigDB:

```
CP <- msigdb_gsets("Homo sapiens", "C2", "CP")
```

With this, I'm expecting to get 2199 gene sets including BIOCARTA, KEGG, PID, REACTOME and more listed here: http://software.broadinstitute.org/gsea/msigdb/collection_details.jsp#CP But instead it returns an object with 29 gene sets.

```
length(CP$genesets)
[1] 29
```

Any idea why this would happen? Is this something caused by `msigdbr`?

Thanks much!

**Comment by anfederico** [comment]
`hypeR` wraps around the `msigdbr` package. It seems as though you cannot request the CP pathways like this, otherwise it would (or should) work in `hypeR`.  I'd pull those genesets with `msigdb_download()` independently and just merge them.

**Comment by igordot** [comment]
If anyone is curious, some clarification about the number of retrieved gene sets can be found here: https://github.com/igordot/msigdbr/issues/4
