### ISSUE TITLE
Issue fetching rgsets - GitHub API error (404)

### ISSUE THREAD

**Issue by manostz** [montilab/hypeR#15]
Hi,
I am using hypeR version 1.2.0 installed by Bioconductor version 3.10 (R 3.6.1). The only issue I have with the package is with rgsets, it seems that available rgsets are not found. See image attached: 

![image](https://user-images.githubusercontent.com/59666581/72011984-fc3a9600-3228-11ea-9230-0cdbfb324da5.png)

Is this my issue or a GitHub API one?

Thank you for your help,
Manos

**Comment by anfederico** [comment]
Yes, there was an argument definition change for this function. Try this:

```
hyperdb_info()
genesets <- hyperdb_rgsets("REACTOME", "70.0")
```

See https://montilab.github.io/hypeR-docs/articles/docs/data.html for more information.

**Comment by manostz** [comment]
Thank you, it worked.
