### ISSUE TITLE
Can I save interactive hyp_emap and keep its features?

### ISSUE THREAD

**Issue by manostz** [montilab/hypeR#16]
Is there a way to save interactive hyp_emap objects (as an htlm?) and keep its features like zooming/collapsing etc? Whenever I try to save the object as an htlm using the RStudio interface I get the following error:
Error: pandoc document conversion failed with error 127

**Comment by anfederico** [comment]
The best way to save plots generated with `hyp_emap()` is to use it in the context of an R markdown document. Something like:

```
```{r fig.width=12, fig.height=12}
hyp_emap(hyp)

...
```

Or you could generate the markdown report with the plot from an R script using `rmarkdown::render()`
