### ISSUE TITLE
Cannot download genesets

### ISSUE THREAD

**Issue by ahussain01** [montilab/hypeR#17]
Hi hypeR developers,

I am currently using your hypeR package on R 4.0.0 and I am having trouble downloading the genesets. I get the following errors. I was using hypeR over a month ago and was having no issue with it at all.

Error in msigdb_download_all(species = "Homo sapiens") : 
  could not find function "msigdb_download_all"

Error in msigdb_fetch(msigdb_path, "C2.CP.BIOCARTA") : 
  could not find function "msigdb_fetch"

Please help.

Thanks

**Comment by anfederico** [comment]
We've introduced some changes to how genesets are downloaded to improve reproducibility of workflows in recent versions. 

You can't bulk download all msigdb genesets but you can see all the available and download/save the ones you need.

```R
library(hypeR)

hypeR::msigdb_info()

gsets <- msigdb_download(species="Homo sapiens", category="C2", "CP:BIOCARTA")
```

**Comment by ahussain01** [comment]
Thanks a tonne.
