### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Henkej77** [montilab/hypeR#18]
Great package! For someone that is new to working in R I very much appreciate the ease, documentation and tutorials. 
I have some suggestions on what I would find useful additions to improve interpretation of biological data:
1.	Introduce a fold enrichment in addition to p-value and FDR. Have seen it defined as fold enrichment = (b/n) / (B/N), where, N - the total number of genes, B - the total number of genes associated with a specific geneset, n - the number of genes in the top or bottom of the user's input list for ranked or in the target set for unranked, b - the number of genes in the intersection. With weighted signatures it would be informative with an option of calculating fold enrichment based on values (e.g. log2 ratio) supplied. 
2.	From my experience with weighted signatures with the kstest test, enrichment is returned for genesets enriched in the top of the signature only. When comparing samples I find it informative to also know what is enriched at the bottom of the signature. Often you see shifts in geneset enrichment between samples from top to bottom of the list, and vice versa. An option to also output genesets at the bottom of the lists would be very informative to me. To separate genesets that are enriched at the top and the bottom of the signature, a minus could be added to the –log10(FDR/p-value). This way, genesets at the top of the list will be positive and those at the bottom negative and easily separated in dotplot or heatmap.
3.	For large datasets with many samples I find it useful to use a heatmap to display enrichment with positive and negative –log10(p-values/FDR) for enrichment in the top and bottom of the list. However, genesets with few genes will have larger p-values so doing a similar plot with fold enrichment would be informative. But then some geneset may show fold enrichment but no significance. Alternatively, a combined score of p-value and fold enrichment could be calculated. For example by summing or multiplying the –log10(p-value/FDR) and fold enrichment. Using log2 as fold change would give givening a minus values for enrichment in bottom and positive values at the top of the signature. 
4.	In the plot from hyp_dots I take it that the size is based on the number of genes in the geneset? Is this the number that were overlapping with the signature? In one of my enrichments there were large differences in the number of genes in the different genesets and some geneset had a very small dot that was difficult to see. It would be good to be able to customize the dot sizes. Add log based on nr of genes in the geneset? Also, the legend for nr of genes in the geneset is missing. In the legend and x-axis, the smallest FDR is missing for me. Could the tics and color range be customizable? For the hyp_dots it would also be good to be able to choose if you want to display FDR or fold enrichment on the X-axis. Color and size could then be chosen as FDR, fold enrichment or nr of genes in the geneset. Personally, I prefer white background with grey lines. But now we are getting into a lot of custmiztion as in the ggplot area I guess. Can you take the hyp_dots and make it into a ggplot object for further customization or make your own template in ggplot and use in hypeR?
5.	When I get data from an omics experiment it is always with samples as columns and gene symbols as rows and when I import it into R it will be a data frame. To me, it would be good with an example on how to do weighted ranked analysis with multiple samples. Output would preferentially be enrichment of genesets (FDR, combined FDR & fold change score) both at the top and the bottom of signature. I would prefer some heatmap to view results. Could be clustered to find differences in geneset usage between samples. Changing from data frame to the format that hypeR requires is challenging for me. Do you know any tutorial for that? Some basic use in some more tutorial as suggested above would be most welcome. 
6.	When comparing 2 (or more groups) of samples and performing a statistical test to define 2 unranked lists of up and down regulated genes, it would be informative to be able to do the enrichment of both the up and down regulated lists and then visualize the results together. For example, using the ratios in the comparison to define what is enriched in the up and down regulated lists, respectively. In a dotplot, x-axis could be ratio (mean, median, boxplot) of the genes from the geneset and color FDR. 
Best
Henrik

**Comment by anfederico** [comment]
Henrik, thanks for the feedback! I'll put some thought into your suggestions and see what I can do.

**Comment by Henkej77** [comment]
Great!
I would be happy to discuss my suggestions further if you like.
Best
Henrik

Henrik Johansson | PhD
Cancer Proteomics| Mass Spectrometry
Dept. Oncology-Pathology | Karolinska Institutet
Science for Life Laboratory | Alfa floor 1| Tomtebodavägen 23A
Box 1031 | SE-171 21 Solna | Sweden
Phone +46 8 524 81210 | Cell +46 769 471179
scilifelab.se<http://scilifelab.se> | ki.se/en/onkpat/janne-lehtios-group<http://ki.se/en/onkpat/janne-lehtios-group> | lehtiolab.se<http://lehtiolab.se>

**Comment by anfederico** [comment]
Closing / archiving this for now.
