### ISSUE TITLE
Cannot download genesets (have tried solutions from previous issues)

### ISSUE THREAD

**Issue by ttz12** [montilab/hypeR#19]
Hi, I’m new to R and am running into some issues following the vignette for HypeR with fetching geneset databases (I looked through the closed issues but they don’t solve it for me).
I’m using R version 3.6.3 and hypeR_1.2.0. Apologies if I'm missing something basic and thanks for your help.

<img width="593" alt="Screenshot 2020-05-30 at 17 21 12" src="https://user-images.githubusercontent.com/47604300/83333731-fc036b80-a299-11ea-889e-e52e22ccd859.png">

**Comment by anfederico** [comment]
Please update to the latest version of hypeR with:

`devtools::install_github("montilab/hypeR")`

The data page on the docs should help with downloading the genesets you're interested in! You can access it [here](https://montilab.github.io/hypeR-docs/index.html).

**Comment by ttz12** [comment]
Thank you, it's working now.
