### ISSUE TITLE
GSEA arguement not recognised hypeR

### ISSUE THREAD

**Issue by Mbxlasi** [montilab/hypeR#29]
Hi I hope you can help.
I have tried to perform GSEA using hype R and using the following code:
hyp_obj <- hypeR(weighted.signature, genesets, test="gsea", background=30000)

However I am met with the following error:
Error in match.arg(test) : 
  'arg' should be one of “hypergeometric”, “kstest”

It doesn't seem to recognise the gsea argument as layed out in the user guide. It works fine for the hypergeometric so I know my genes are recognised and I have tried passing the weighted signature in the same format as the guide to no avail. 
Thank you for your time.

**Comment by anfederico** [comment]
The _kstest_ method will accept either a weighted or unweighted signature. If you're looking for computing permutation-based significance like in the original GSEA method, try out [fgsea](https://bioconductor.org/packages/release/bioc/html/fgsea.html). You can format the output into a `hyp` object and use the downstream methods of hypeR.
