### ISSUE TITLE
Error in conexion

### ISSUE THREAD

**Issue by AnaBVA** [montilab/hypeR#30]
Hi! 
Your package is very useful, thanks. 
I've used `hypeR` for a couple of months but today I got a client error 404 by doing:
`enrichr_gsets("Jensen_DISEASES")`  or `enrichr_gsets("GO_Biological_Process_2018")`  basically with any Enrichr DB and I got this error: 
`Error in enrichr_connect(.format_str("geneSetLibrary?mode=text&libraryName={1}",  : 
  Client error: (400) Bad Request` 

Thank you for your help.

I recently update some packages and I don't know if it is causing conflicts. 

`> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS  10.16                
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Mexico_City         
 date     2021-03-08                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────
 package      * version  date       lib source        
 abind          1.4-5    2016-07-21 [1] CRAN (R 4.0.0)
 assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
 backports      1.2.1    2020-12-09 [1] CRAN (R 4.0.2)
 BiocManager    1.30.10  2019-11-16 [1] CRAN (R 4.0.0)
 broom          0.7.5    2021-02-19 [1] CRAN (R 4.0.2)
 cachem         1.0.4    2021-02-13 [1] CRAN (R 4.0.2)
 callr          3.5.1    2020-10-13 [1] CRAN (R 4.0.2)
 car            3.0-10   2020-09-29 [1] CRAN (R 4.0.2)
 carData        3.0-4    2020-05-22 [1] CRAN (R 4.0.0)
 cellranger     1.1.0    2016-07-27 [1] CRAN (R 4.0.0)
 cli            2.3.1    2021-02-23 [1] CRAN (R 4.0.2)
 codetools      0.2-18   2020-11-04 [1] CRAN (R 4.0.2)
 colorspace     2.0-0    2020-11-11 [1] CRAN (R 4.0.2)
 cowsay         0.8.0    2020-02-06 [1] CRAN (R 4.0.2)
 crayon         1.4.1    2021-02-08 [1] CRAN (R 4.0.2)
 curl           4.3      2019-12-02 [1] CRAN (R 4.0.0)
 data.table     1.14.0   2021-02-21 [1] CRAN (R 4.0.2)
 DBI            1.1.1    2021-01-15 [1] CRAN (R 4.0.2)
 desc           1.3.0    2021-03-05 [1] CRAN (R 4.0.2)
 devtools       2.3.2    2020-09-18 [1] CRAN (R 4.0.2)
 digest         0.6.27   2020-10-24 [1] CRAN (R 4.0.2)
 dplyr          1.0.5    2021-03-05 [1] CRAN (R 4.0.2)
 ellipsis       0.3.1    2020-05-15 [1] CRAN (R 4.0.0)
 evaluate       0.14     2019-05-28 [1] CRAN (R 4.0.0)
 fansi          0.4.2    2021-01-15 [1] CRAN (R 4.0.2)
 farver         2.1.0    2021-02-28 [1] CRAN (R 4.0.2)
 fastmap        1.1.0    2021-01-25 [1] CRAN (R 4.0.2)
 forcats        0.5.1    2021-01-27 [1] CRAN (R 4.0.2)
 foreign        0.8-81   2020-12-22 [1] CRAN (R 4.0.2)
 fortunes       1.5-4    2016-12-29 [1] CRAN (R 4.0.2)
 fs             1.5.0    2020-07-31 [1] CRAN (R 4.0.2)
 generics       0.1.0    2020-10-31 [1] CRAN (R 4.0.2)
 ggforce        0.3.3    2021-03-05 [1] CRAN (R 4.0.2)
 ggplot2        3.3.3    2020-12-30 [1] CRAN (R 4.0.2)
 ggpubr         0.4.0    2020-06-27 [1] CRAN (R 4.0.2)
 ggsignif       0.6.1    2021-02-23 [1] CRAN (R 4.0.2)
 glue           1.4.2    2020-08-27 [1] CRAN (R 4.0.2)
 gridExtra      2.3      2017-09-09 [1] CRAN (R 4.0.0)
 gtable         0.3.0    2019-03-25 [1] CRAN (R 4.0.0)
 haven          2.3.1    2020-06-01 [1] CRAN (R 4.0.0)
 here           1.0.1    2020-12-13 [1] CRAN (R 4.0.2)
 hms            1.0.0    2021-01-13 [1] CRAN (R 4.0.2)
 htmltools      0.5.1.1  2021-01-22 [1] CRAN (R 4.0.2)
 htmlwidgets    1.5.3    2020-12-10 [1] CRAN (R 4.0.2)
 httpuv         1.5.5    2021-01-13 [1] CRAN (R 4.0.2)
 httr           1.4.2    2020-07-20 [1] CRAN (R 4.0.2)
 hypeR        * 1.6.0    2020-10-27 [1] Bioconductor  
 igraph         1.2.6    2020-10-06 [1] CRAN (R 4.0.2)
 inline         0.3.17   2020-12-01 [1] CRAN (R 4.0.2)
 jsonlite       1.7.2    2020-12-09 [1] CRAN (R 4.0.2)
 kableExtra     1.3.4    2021-02-20 [1] CRAN (R 4.0.2)
 knitr          1.31     2021-01-27 [1] CRAN (R 4.0.2)
 later          1.1.0.1  2020-06-05 [1] CRAN (R 4.0.0)
 lifecycle      1.0.0    2021-02-15 [1] CRAN (R 4.0.2)
 loo            2.4.1    2020-12-09 [1] CRAN (R 4.0.2)
 magrittr       2.0.1    2020-11-17 [1] CRAN (R 4.0.2)
 MASS           7.3-53.1 2021-02-12 [1] CRAN (R 4.0.2)
 matrixStats    0.58.0   2021-01-29 [1] CRAN (R 4.0.2)
 memoise        2.0.0    2021-01-26 [1] CRAN (R 4.0.2)
 mime           0.10     2021-02-13 [1] CRAN (R 4.0.2)
 msigdbr        7.2.1    2020-10-02 [1] CRAN (R 4.0.2)
 munsell        0.5.0    2018-06-12 [1] CRAN (R 4.0.0)
 openxlsx       4.2.3    2020-10-27 [1] CRAN (R 4.0.2)
 packrat        0.5.0    2018-11-14 [1] CRAN (R 4.0.0)
 pillar         1.5.1    2021-03-05 [1] CRAN (R 4.0.2)
 pkgbuild       1.2.0    2020-12-15 [1] CRAN (R 4.0.2)
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.0.0)
 pkgload        1.2.0    2021-02-23 [1] CRAN (R 4.0.2)
 plyr           1.8.6    2020-03-03 [1] CRAN (R 4.0.2)
 polyclip       1.10-0   2019-03-14 [1] CRAN (R 4.0.2)
 prettyunits    1.1.1    2020-01-24 [1] CRAN (R 4.0.0)
 processx       3.4.5    2020-11-30 [1] CRAN (R 4.0.2)
 promises       1.2.0.1  2021-02-11 [1] CRAN (R 4.0.2)
 ps             1.6.0    2021-02-28 [1] CRAN (R 4.0.2)
 purrr          0.3.4    2020-04-17 [1] CRAN (R 4.0.0)
 R6             2.5.0    2020-10-28 [1] CRAN (R 4.0.2)
 Rcpp           1.0.6    2021-01-15 [1] CRAN (R 4.0.2)
 RcppParallel   5.0.3    2021-02-24 [1] CRAN (R 4.0.2)
 reactable      0.2.3    2020-10-04 [1] CRAN (R 4.0.2)
 readxl         1.3.1    2019-03-13 [1] CRAN (R 4.0.0)
 remotes        2.2.0    2020-07-21 [1] CRAN (R 4.0.2)
 reshape2       1.4.4    2020-04-09 [1] CRAN (R 4.0.0)
 rio            0.5.26   2021-03-01 [1] CRAN (R 4.0.2)
 rlang          0.4.10   2020-12-30 [1] CRAN (R 4.0.2)
 rmarkdown      2.7      2021-02-19 [1] CRAN (R 4.0.2)
 rmsfact        0.0.3    2016-08-04 [1] CRAN (R 4.0.2)
 rprojroot      2.0.2    2020-11-15 [1] CRAN (R 4.0.2)
 rstan          2.21.2   2020-07-27 [1] CRAN (R 4.0.2)
 rstatix        0.7.0    2021-02-13 [1] CRAN (R 4.0.2)
 rstudioapi     0.13     2020-11-12 [1] CRAN (R 4.0.2)
 rvest          0.3.6    2020-07-25 [1] CRAN (R 4.0.2)
 scales         1.1.1    2020-05-11 [1] CRAN (R 4.0.0)
 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 4.0.2)
 shiny          1.6.0    2021-01-25 [1] CRAN (R 4.0.2)
 StanHeaders    2.21.0-7 2020-12-17 [1] CRAN (R 4.0.2)
 stringi        1.5.3    2020-09-09 [1] CRAN (R 4.0.2)
 stringr        1.4.0    2019-02-10 [1] CRAN (R 4.0.0)
 svglite        2.0.0    2021-02-20 [1] CRAN (R 4.0.2)
 systemfonts    1.0.1    2021-02-09 [1] CRAN (R 4.0.2)
 testthat       3.0.2    2021-02-14 [1] CRAN (R 4.0.2)
 tibble         3.1.0    2021-02-25 [1] CRAN (R 4.0.2)
 tidyr          1.1.3    2021-03-03 [1] CRAN (R 4.0.2)
 tidyselect     1.1.0    2020-05-11 [1] CRAN (R 4.0.0)
 tweenr         1.0.1    2018-12-14 [1] CRAN (R 4.0.2)
 usethis        2.0.1    2021-02-10 [1] CRAN (R 4.0.2)
 utf8           1.1.4    2018-05-24 [1] CRAN (R 4.0.0)
 V8             3.4.0    2020-11-04 [1] CRAN (R 4.0.2)
 vctrs          0.3.6    2020-12-17 [1] CRAN (R 4.0.2)
 viridisLite    0.3.0    2018-02-01 [1] CRAN (R 4.0.0)
 visNetwork     2.0.9    2019-12-06 [1] CRAN (R 4.0.0)
 webshot        0.5.2    2019-11-22 [1] CRAN (R 4.0.0)
 withr          2.4.1    2021-01-26 [1] CRAN (R 4.0.2)
 xfun           0.21     2021-02-10 [1] CRAN (R 4.0.2)
 xml2           1.3.2    2020-04-23 [1] CRAN (R 4.0.0)
 xtable         1.8-4    2019-04-21 [1] CRAN (R 4.0.0)
 zip            2.1.1    2020-08-27 [1] CRAN (R 4.0.2)`

**Comment by anfederico** [comment]
Sorry about that, the domain for Enrichr's API was changed. Fixed now!
