### ISSUE TITLE
reactable should be "wider"

### ISSUE THREAD

**Issue by tetomonti** [montilab/hypeR#32]
When generating a reactable for mhyp objects, the size of the nested tables is such that often the 'hits' column is cropped. See, e.g., here:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/9437983/122789799-affcdd80-d285-11eb-8f9e-0a9b0d310eff.png">

Ideally, the table should be wider so as to allow for easier inspection of overlap hits.

**Comment by anfederico** [comment]
We could make the Hits column bigger, although the Label column is prioritized by default. You should be able to resize columns in reactable. If you hover over the column labels, a resize cursor should appear.
