### ISSUE TITLE
Enrichment maps unable to export in a .tiff format

### ISSUE THREAD

**Issue by morgancy711** [montilab/hypeR#33]
The enrichment maps open up in the viewer, and are then unable to be exported in a .tiff format, but can in a .png and .jpg format. This is more of an annoyance than anything else as the enrichment map node label often overlap and intersect, making it hard to determine which label goes with which node.

**Comment by anfederico** [comment]
The enrichment and hierarchy maps were initially intended for interactive visualization for redundant genesets but we are working on a high quality export solution for network figures. In the meantime there are a couple of things you could do.

1. Use some of the `hyp_emap()` code to recreate an `igraph` object for static plotting. This will let you fully customize your network figure and export to any resolution/format.
2. Save the output from `hyp_emap()` or `hyp_hmap()` to a high resolution.

```R
vn <- hyp_hmap(hyp)
vn <- visOptions(vn, width="5000px", height="5000px")
visNetwork::visSave(vn, "plot.html")
```

If you open the file in a web browser and immediately right-click / save, the network plot will be in high resolution, although not TIFF. With this route you can interactively adjust it before hand.

If you need to do this from a script - I've had some success with this snippet.
```R
library(webshot)
if (Sys.which("phantomjs") == "") webshot::install_phantomjs()
tmp <- tempfile(fileext=".html")
vn <- hyp_hmap(hyp)
vn <- visOptions(vn, width="5000px", height="5000px")
visNetwork::visSave(vn, tmp)
webshot::webshot(tmp, selector=c("canvas"), zoom=1, file="plot.png")
```

Regarding the overlapping labels, you could interactively adjust the nodes to give them some more room. We can add a label trimming solution for these plots, but in the meantime you could simply pre-trim your geneset labels if they are long. Maybe subset on the first 16 characters?

**Comment by anfederico** [comment]
This is address in the latest version, please refer to the documentation.
