### ISSUE TITLE
error in GSEA about weighted signatures

### ISSUE THREAD

**Issue by viviyanran** [montilab/hypeR#36]
I conducted the function hypeR: hyp_obj <- hypeR(signature, geneset_1,fdr=0.05,plotting = T,test = 'kstest'), the signature is weighted, but it returned Error in apply(results[, c("score", "pval", "geneset", "overlap")], 2,  : dim(X) must have a positive length. And my geneset was a custom geneset.
I cannot get the plot.

**Comment by anfederico** [comment]
Could you show the format of your signature and custom geneset?
