### ISSUE TITLE
hyp_to_excel: zip::zip() is deprecated

### ISSUE THREAD

**Issue by montilab** [montilab/hypeR#4]
When running hyp_to_excel, the following warning is output:
`Note: zip::zip() is deprecated, please use zip::zipr() instead`
`[1] 1 1 1 1 1 1 1`

**Comment by anfederico** [comment]
This is odd, was this in R >= 3.5 and/or on a cluster computing environment? Perhaps an old version of `openxlsx` is causing the warning.

**Comment by anfederico** [comment]
Errors shouldn't persist on new versions of R.
