### ISSUE TITLE
X-axis and Outputting Gene Overlap Size

### ISSUE THREAD

**Issue by NicNikoloutsos** [montilab/hypeR#42]
Hi, very nice package, thank you for making it!

I am confused as to what the x-axis FDR represents after calling hyp_plot on a hyp object. Is this different from the color coded FDR or is it the same values and redundant info?

![image](https://user-images.githubusercontent.com/53197641/150419206-00c0963d-357d-4e6e-bc50-69e5dd74c43c.png)

I would also like to know if it would be possible to output the gene overlap or gene ratio size alongside the dots.

Thank you for your time!

**Comment by anfederico** [comment]
The x-axis is the significance of the overlap. It can be p-values or adjusted p-values (FDR). And yes the coloring is redundant. This is a similar issue to #35. I'm planning on updating this plot with more options - I can definitely consider adding gene overlap / size ratio in the margins as well, that's a good suggestion.

**Comment by anfederico** [comment]
This has been updated and closed in #35. Please refer to that issue or re-open this one if you have further questions.
