### ISSUE TITLE
What's the issue with FDR ?

### ISSUE THREAD

**Issue by gyanmishra** [montilab/hypeR#7]
Hi, 

I tried to run hypeR on my datasets, however I am always getting pval and fdr as value 1. Could you please check what's an issue here. 

https://ibb.co/9ZtKvL1

**Comment by anfederico** [comment]
All of the geneset symbols are upper case, so convert your signature genes to upper case as well.

**Comment by gyanmishra** [comment]
I am still getting the similar result with "hypergeometric" test ,all the pathways are coming with pval and fdr value of 1 and not showing any gene overlap,  however its working with with "kstest" .

**Comment by anfederico** [comment]
If your symbols are upper case, and the p-values are 1, then your signature may not be enriched with any genesets.

**Comment by anfederico** [comment]
You could try another geneset compendium, like Hallmark or Reactome.

**Comment by gyanmishra** [comment]
I think there is some issue, when I am using "hypergeometric", else everything is working fine with "kstest"

**Comment by anfederico** [comment]
Could you send me a script to reproduce your issue?

Or reply with your code and show what the input signature looks like for both the hypergeometric and kstest methods. That way I can let you know if it is your data or an issue with the package.

**Comment by gyanmishra** [comment]
[DE_genes_ranks.txt](https://github.com/montilab/hypeR/files/3266855/DE_genes_ranks.txt)

**Comment by gyanmishra** [comment]
[DE_genes_ranks.txt](https://github.com/montilab/hypeR/files/3266871/DE_genes_ranks.txt)

```
library(hypeR)
ranks  <- deframe(read.table("DE_genes_ranks.txt",sep = "\t",header = T))
head(ranks)
msigdb_path <- msigdb_download_all(species="Mus musculus")
KEGG <- msigdb_fetch(msigdb_path, "C2.CP.KEGG")
hyp_obj <- hypeR(ranks, Reactome, test="hypergeometric")
hyp_show(hyp_obj)
hyp_obj <- hypeR(ranks, KEGG, test="kstest")
hyp_show(hyp_obj)
Reactome <- msigdb_fetch(msigdb_path, "C2.CP.REACTOME")
hyp_obj <- hypeR(ranks, Reactome, test="hypergeometric")
hyp_show(hyp_obj)
hyp_obj <- hypeR(ranks, Reactome, test="kstest")
hyp_show(hyp_obj)
```

**Comment by anfederico** [comment]
This is working now on my end, you need to convert your rankings to a character vector of gene symbols when using `test="hypergeometric"`. See my comments.

```R
library(tidyverse)
library(hypeR)

ranks  <- deframe(read.table("DE_genes_ranks.txt",sep = "\t",header = T))
head(ranks)

msigdb_path <- msigdb_download_all(species="Mus musculus")
KEGG <- msigdb_fetch(msigdb_path, "C2.CP.KEGG")
hyp_obj <- hypeR(ranks, KEGG, test="kstest")
hyp_show(hyp_obj)

# Hypergeometric method takes a character vector of gene symbols
# This should be a differential expression signature for example (top 100 differentially expressed genes)
signature <- names(sort(ranks, decreasing=TRUE)[1:100])
head(signature)

hyp_obj <- hypeR(signature, KEGG, test="hypergeometric")
hyp_show(hyp_obj)
```

**Comment by gyanmishra** [comment]
Thanks Federico, now I got it. Hypergeometric test would be overlap of signature genes with genesets. That's why there were no overlap and hence pval were coming as 1.
 Nice simplified and comprehensive tool for gene set enrichment analysis with better visualisation. 

Thanks 
Gyan

**Comment by anfederico** [comment]
Thanks :)
