### ISSUE TITLE
Enrichment tables should report background and signature size

### ISSUE THREAD

**Issue by tetomonti** [montilab/hypeR#8]
Since these are 'constant' across genesets, they should be reported once, perhaps on top of the table (if possible).

**Comment by tetomonti** [comment]
Ideally, background and signature size should not be reported in the table but, say, above, since they are the same in each row, and needlessly take up space.

**Comment by anfederico** [comment]
I thought about this, we could potentially make a custom table with reactable:

Examples:
https://glin.github.io/reactable/articles/nba-box-score/nba-box-score.html
https://glin.github.io/reactable/articles/womens-world-cup/womens-world-cup.html

**Comment by anfederico** [comment]
This will be addressed and fixed in the next update.
